### ISSUE TITLE
shared目录下没有data_collect?

### ISSUE THREAD

**Issue by songroom2016** [SheldonNico/ctp-rs#2]
shared
├── data_collect
│   ├── unix.x86_64
│   │   ├── libLinuxDataCollect.so -> LinuxDataCollect.so
│   │   └── LinuxDataCollect.so
│   ├── windows.x86
│   │   ├── WinDataCollect.dll
│   │   └── WinDataCollect.lib
│   └── windows.x86_x64
│       ├── WinDataCollect.dll
│       └── WinDataCollect.lib

找不到相应的libLinuxDataCollect.so -> LinuxDataCollect.so
│   │   └── LinuxDataCollect.so

sg@DESKTOP-MEDPUTU:~/ctp_rs_0215$ tree shared
shared
└── include
    ├── DataCollect.h
    ├── ThostFtdcMdApi.h
    ├── ThostFtdcTraderApi.h
    ├── ThostFtdcUserApiDataType.h
    └── ThostFtdcUserApiStruct.h

1 directory, 5 files
哪里可以下载？

**Comment by songroom2016** [comment]
//println!("cargo:rustc-link-search={}", root.join("shared/data_collect").join(format!("{}.{}", platform, arch)).display());

    // if platform == "unix" {
    //     println!("cargo:rustc-link-lib=dylib=LinuxDataCollect");
    // } else {
    //     println!("cargo:rustc-link-lib=dylib=WinDataCollect");
    // }

把build.rs中上面注释掉后，可以运行了。

**Comment by SheldonNico** [comment]
不好意思回复晚了，ctp的库文件是ctp提供的，可以到这里下载 [ctp sdk](http://www.sfit.com.cn/5_2_DocumentDown_2.htm)，因为rustc找lib的时候需要以libXXX.so的格式，所以我建了个软连接(这个文件实际就是不带lib的so文件)
```bash
cd /shared/data_collect/unix.x86_64
ln -s LinuxDataCollect.so libLinuxDataCollect.so
```

同理 thosttraderapi_se.so 和 thostmduserapi_se.so 都是这样操作了一遍，build.rs 理论上要link到才行，注释掉能跑可能因为没有用 LinuxDataCollect?

**Comment by songroom2016** [comment]
对的，我没有用datacollect
