### ISSUE TITLE
找不到.so文件

### ISSUE THREAD

**Issue by rain2307** [SheldonNico/ctp-rs#3]
你好，这个项目我构建成功了，更新了6.6.9的版本，examples的文件我不知道怎么跑，于是new了一个新项目，将md的例子拷贝到main.rs下 cargo run.

在Cargo.toml里引入
```toml
ctp_rs = { path = "../../xxx/ctp-rs" }
```

一开始是报的找不到 DataCollect 那三个库文件，加了lib前缀之后报错变了，如下所示:
`error while loading shared libraries: libthostmduserapi_se.so: cannot open shared object file: No such file or directory`

请问这个该如何解决呢？我在ctp-rs 目录重新build了，报错是有变化，说明是生效了，但是还是有问题。现在我把shared拷贝到这个单独的项目也不起作用。🙏

**Comment by SheldonNico** [comment]
抱歉，README里的关于so文件的说明有点混乱，其实只要项目能够找到so文件即可。
我最新的文件树是这样的

![image](https://user-images.githubusercontent.com/11974052/223048038-c66b71e7-f9af-4037-8d56-010bae935a46.png)

代码里链接的部分在这里 [link](https://github.com/SheldonNico/ctp-rs/blob/master/build.rs#L18-L32)，link部分可以自己改，改到自己放so的地方即可，DataCollect 那个确实是不需要的，重要的是另外两个。

参考我截图里的文件树，把文件夹建好，so文件移过去，用 ln -s 给 thostXXX.so 创建 libthostXXX.so 的符号链接（或者直接重命名都可以），用下面link的代码替换掉现在git里配置的部分即可。

```rust
println!("cargo:rustc-link-search={}", root.join("shared").join(format!("{}.{}", platform, arch)).display());
println!("cargo:rustc-link-lib=dylib=thostmduserapi_se");
println!("cargo:rustc-link-lib=dylib=thosttraderapi_se");  
```

cargo b --example=tdapi 没有报错即已经好了（看你的报错 loading好像是运行时候报错，即这一步已经完成了，可以直接继续），但直接 cargo run 或者直接运行binary还可能报错，因为 build 和 运行时 的so文件是两码事，我这边我是在home下建立了一个文件夹来放所有的依赖库的，像下面的截图这样，可以看到还是用 ln -s 建的符号链接。然后运行的时候需要指定好so所在的位置，以类似这条命令运行的 `LD_LIBRARY_PATH=/home/xnie/.local/lib ../../target/debug/examples/tdapi`。如果嫌麻烦，可以在 .bashrc 等位置用export配置。但CTP穿透版本跑的时候需要root，一般root的环境是共用的不建议改动，每次跑的时候指定参数是比较好的

![image](https://user-images.githubusercontent.com/11974052/223051225-fd59704b-b246-486c-861f-de16de7cd93b.png)

**Comment by rain2307** [comment]
@SheldonNico 非常详细，太感谢了❤️。设置LD_LIBRARY_PATH之后解决了，好人一生平安

**Comment by guotie** [comment]
请教一下：

```
println!("cargo:rustc-link-lib=dylib=thostmduserapi_se");
println!("cargo:rustc-link-lib=dylib=thosttraderapi_se");  
```

为什么需要这两句？

我直接用bindgen，没有这两句就ld不成功，有了这两句才能成功

**Comment by SheldonNico** [comment]
这就是告诉编译器，需要 link 到相应的library (CTP 开发包里提供的 `thostmduserapi_se`和`thosttraderapi_se`)，相当于 gcc 编译的 `-l` 参数，在 bindgen 的 [tutorial](https://rust-lang.github.io/rust-bindgen/tutorial-3.html?highlight=link#create-a-buildrs-file) 里说明了(这两个库是动态链接库，所以是 dylib )

**Comment by guotie** [comment]
thanks
