### ISSUE TITLE
pRspInfo 打印出来是 0x0 怎么办

### ISSUE THREAD

**Issue by rain2307** [SheldonNico/ctp-rs#4]
系统:  Ubuntu 22.04.2 LTS
rustc 1.68.2 (9eb3afe9e 2023-03-27)
trader_api: v6.6.9_20220914

您好，我在实现 trader api 的时候，在 simnow 查询合约的接口的 pRspInfo 字段打印出来是 `0x0`，访问字段就会崩溃。
该接口其余字段都是正常的，前面连接、登录的接口该字段也都是正常的。
请问这个是什么原因呢？该怎么解决啊

```rust
impl Rust_CThostFtdcTraderSpi_Trait for Spi {
  fn on_rsp_qry_instrument(
          &mut self, pInstrument: *mut ctp_api::CThostFtdcInstrumentField,
          pRspInfo: *mut ctp_api::CThostFtdcRspInfoField, nRequestID: std::os::raw::c_int, bIsLast: bool,
      ) 
}
```

**Comment by SheldonNico** [comment]
意思是 pRspInfo 拿到的NULL的指针，如果 pInstrument 是非空的就是正常现象，可以查看 CTP的文档 看下具体是怎么约束的。我用下来发现 请求回报有两种方式表示当前这条回报没有报错，一是 `pRspInfo.is_null()` ，二是 pRspInfo 非空，但 `(&*pRspInfo).ErrorID == 0`

**Comment by rain2307** [comment]
如果是正常的那就没问题了。
查看6.6.9的接口说明好像没有提到会为空指针。
谢谢大佬回复
