### ISSUE TITLE
编译出错，`Rust_CThostFtdcMdSpi_Trait` not found in source code

### ISSUE THREAD

**Issue by leodo** [SheldonNico/ctp-rs#6]
PS D:\Project\develop\ctp-rs> cargo build
   Compiling ctp_rs v0.1.0 (D:\Project\develop\ctp-rs)
error: failed to run custom build command for `ctp_rs v0.1.0 (D:\Project\develop\ctp-rs)`

Caused by:
  process didn't exit successfully: `D:\Project\develop\ctp-rs\target\debug\build\ctp_rs-0cb50a7ff6556736\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at build.rs:100:9:
  `Rust_CThostFtdcMdSpi_Trait` not found in source code
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

重新运行了autobind.py 也不行。

**Comment by SheldonNico** [comment]
看报错好像是 autobind.py 生成的文件出错了，看下 `src/wrapper_ext` 的内容是啥，是不是更新了 `shared/include` 下的头文件？

另外我从没有在Windows上成功运行过，刚刚又试了下卡在 Link 上了，即使解决了 `autobind.py` 的问题之后也可能卡在 Link 上。我试下能不能解决

**Comment by leodo** [comment]
我现在在看 https://gitee.com/kozyan/ctp-rs  这个可以运行，这个人应该是借鉴你的项目

**Comment by SheldonNico** [comment]
我尝试更新了 `rust-bindgen` 后，在 windows 10 上编译成功了，如果还需要的话。

**Comment by leodo** [comment]
优秀！ 感谢！ 编译成功了！
